title: mxjr/help
description: mxjr/help
author: Michael Raskey
github_username: mxjr
repo: https://github.com/mxjr/help

url: https://mxjr.github.io
baseurl: /help

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
remote_theme: jekyll/minima
titles_from_headings:
  enabled: true
  collections: true
  strip_title: true

